Short term fix for undefined function
While trying to compile for ARM Mac, got the following error in hdf5:
/Users/runner/work/kissplice-ci-clone/kissplice-ci-clone/bcalm/gatb-core/gatb-core/thirdparty/hdf5/src/H5Odeprec.c:141:8: error: call to undeclared function 'H5CX_set_apl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if(H5CX_set_apl(&lapl_id, H5P_CLS_LACC, loc_id, FALSE) < 0)
^
/Users/runner/work/kissplice-ci-clone/kissplice-ci-clone/bcalm/gatb-core/gatb-core/thirdparty/hdf5/src/H5Odeprec.c:195:8: error: call to undeclared function 'H5CX_set_apl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if(H5CX_set_apl(&lapl_id, H5P_CLS_LACC, loc_id, FALSE) < 0)
^
/Users/runner/work/kissplice-ci-clone/kissplice-ci-clone/bcalm/gatb-core/gatb-core/thirdparty/hdf5/src/H5Odeprec.c:322:8: error: call to undeclared function 'H5CX_set_apl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if(H5CX_set_apl(&lapl_id, H5P_CLS_LACC, loc_id, FALSE) < 0)
^

The long term fix is to use an up to date hdf5 (making it an external dependency ?).
In the meantime add a header including the missing declaration.